version: "3.9"

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db_container

  #Node API services
  api:
    build: .
    ports:
      - 4000:3000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017/userRegister
      DB_NAME: CouponsDatabase
      NAME: ApoorvPandey
      ACCESS_TOKEN_SECRET: 815c1b565066e5187f2a4f602f436a52954f7f1ca78c9c8f5b143f62a514f7b9
      REFRESH_TOKEN_SECRET: 23d5da02989e7d4f07f7367b0660e01c9842b827bd05756a5a81cafcf46cc0b9
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
